#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Apr 23 21:19:54 2023

@author: mathaes
"""

LEXILOGIO_MAJOR_VERSION = 0
LEXILOGIO_MINOR_VERSION = 2
LEXILOGIO_PATCH_VERSION = 0

LEXILOGIO_RELEASE_PHASE = 'd'
LEXILOGIO_RELEASE_BUILD = '2'

LEXILOGIO_COPYRIGHT = "Copyright © 2023 Mathaesthetics LLC"
LEXILOGIO_AUTHOR = "Christopher Corbell"
LEXILOGIO_BRIEF_LICENSE = "License: GPL-3.0-or-later"

LEXILOGIO_SHORT_VERSION_STR = f"{LEXILOGIO_MAJOR_VERSION}.{LEXILOGIO_MINOR_VERSION}.{LEXILOGIO_PATCH_VERSION}-{LEXILOGIO_RELEASE_PHASE}{LEXILOGIO_RELEASE_BUILD}"

LEXILOGIO_PRODUCT_VERSION_STR = f"Lexilogio {LEXILOGIO_SHORT_VERSION_STR}"

LEXILOGIO_LONG_VERSION_COPYRIGHT = f"""{LEXILOGIO_PRODUCT_VERSION_STR}
written by {LEXILOGIO_AUTHOR}
{LEXILOGIO_BRIEF_LICENSE}
{LEXILOGIO_COPYRIGHT}
"""
